app:
<<<<<<< HEAD

  telegram-token: ${TELEGRAM-API-KEY}



=======
  telegram-token: unset
>>>>>>> origin/hw1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
